### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by Maniues** [kapi2289/fb-anti-unsend#3]
EN: This software isn't licensed. This means that nobody can use this software without permission. Please add license file. I recommend MIT license for this software. You can find another license at https://choosealicense.com/
If you choose GNU GPL as your license, read their guidelines for using the GPL at https://www.gnu.org/licenses/gpl-howto.html.en or read guidelines at the end of gpl text. If you choose GPL, please add a note about using newer versions of GNU GPL.

PL: Te oprogramowanie nie jest udostępnione z licencją. To oznacza, że nikt nie może go używać bez zgody. Proszę, dodaj licencję. Polecam licencję MIT dla tego programu. Jeśli wolisz, możesz znaleźć inną licencję na https://choosealicense.com/ . 
Jeżeli wybierzesz GNU GPL jako licencję, przeczytaj ich wskazówki używania GPL na https://www.gnu.org/licenses/gpl-howto.html.en lub na końcu tekstu GPL. Dodatkowo: jeśli wybierzesz GPL, dodaj informacje o używaniu nowszych wersji GNU GPL.

**Comment by kapi2289** [comment]
Yeah, you're right. It's old, small and not used anymore because of problems with Facebook project so I haven't thought of any license yet. I'll add it, thanks!
